### ISSUE TITLE
Created releases

### ISSUE THREAD

**Issue by Jeeppler** [lsst-sqre/terraform-tinfoil-tiller#4]
Can you create releases and version them according to the Helm release it supports? For example, your release version would be 0.7 for helm provider version 0.7 etc. You could use minor versions if you have to add bug fixes etc.

**Comment by jhoblitt** [comment]
Note that it is possible to set the exact version of tiller used with the `tiller_image` var.  I'm not sure if it is a good idea to try to set tags to a specific version of the helm provider.  Maybe a branch...

**Comment by Jeeppler** [comment]
@jhoblitt a branch would work as well. It is important, that nothing suddenly breaks.

**Comment by jhoblitt** [comment]
I've created branches named `0.7.x`, `0.8.x`, and `0.9.x` on the assumption/hope that the helm version won't change in a patch release of the provider.
